spring:
    application:
        name: frontend-service
hystrix:
    command:
        "RestClientWithFeign#doATask()":
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 2500
